### ISSUE TITLE
Plots doesn't show up

### ISSUE THREAD

**Issue by anelda** [selectsagar/HR-Movement-Dashboard#2]
Hi @sagarkulkarny,

Thanks for this beautiful resource!

I cloned your code and tried to run it locally but none of the plots shows up. Do you have any idea how to solve it? I've been googling.

@Danieldavid521 I am tagging you here (hope you don't mind) as I was wondering if you maybe ran into the same problem when you were running this locally.

Thanks!

**Comment by Danieldavid521** [comment]
yes, I suggest you set the working directory to inside the folder of this project, then edit the main .Rmd file and align the file paths to where the files are on your computer. I just reran this code and it worked. Are you using a Mac Windows or Linux?

**Comment by anelda** [comment]
Thanks so much @Danieldavid521! On Ubuntu. I actually just figured out the plots render when I open the html in a browser, just not in the RStudio pop-up Window. I haven't delved much further into it to understand why. For now, that solves my problem. Thanks for responding!
